#!/usr/bin/env bash
# team-boot session_start script — lean orientation for first user message injection.
# Pure shell (grep/sed), no runtime dependencies.
set -euo pipefail

INIT_FILE=".adlc/init-options.json"

if [ ! -f "$INIT_FILE" ]; then
  echo "<EXTREMELY_IMPORTANT>"
  echo "Team AI directives not configured for this project."
  echo "Run /team-setup to wire in the team constitution, CDR index, PDR/ADR indexes, and skill registry."
  echo "</EXTREMELY_IMPORTANT>"
  exit 0
fi

# Extract team_ai_directives from JSON (pure shell, no runtime deps).
TEAM_AI_DIRECTIVES=$(grep '"team_ai_directives"' "$INIT_FILE" \
  | sed 's/.*"team_ai_directives"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/' \
  | head -1)

# Handle null marker (user opted out) or empty value.
if [ -z "$TEAM_AI_DIRECTIVES" ] || [ "$TEAM_AI_DIRECTIVES" = "null" ]; then
  exit 0
fi

# Verify path exists.
if [ ! -d "$TEAM_AI_DIRECTIVES" ]; then
  echo "<EXTREMELY_IMPORTANT>"
  echo "Team AI directives path not found: $TEAM_AI_DIRECTIVES"
  echo "Run /team-setup to reconfigure."
  echo "</EXTREMELY_IMPORTANT>"
  exit 0
fi

echo "<EXTREMELY_IMPORTANT>"
echo "# Team AI Directives"
echo ""
echo "Path: $TEAM_AI_DIRECTIVES"
echo ""

# Constitution — principle titles only (lean)
echo "## Constitution"
grep '^[0-9]\+\.' "$TEAM_AI_DIRECTIVES/context_modules/constitution.md" 2>/dev/null | head -20 || echo "(not found)"
echo ""

# CDR Index — compact: ID + Type + Descriptor only
# CDR.md is a derived flat table auto-generated by /team-repair from per-dir index.md files.
echo "## CDR Index"
if [ -f "$TEAM_AI_DIRECTIVES/CDR.md" ]; then
  CDR_COUNT=$(awk '/^\| CDR|^\| rule|^\| skill|^\| example|^\| constitution/ {count++} END {print count+0}' "$TEAM_AI_DIRECTIVES/CDR.md" 2>/dev/null || true)
  [[ "$CDR_COUNT" =~ ^[0-9]+$ ]] || CDR_COUNT=0
  awk -F'|' '/^\| CDR|^\| rule|^\| skill|^\| example|^\| constitution/ {gsub(/^ +| +$/,"",$2); gsub(/^ +| +$/,"",$4); gsub(/^ +| +$/,"",$5); print "| " $2 " | " $4 " | " $5 " |"}' "$TEAM_AI_DIRECTIVES/CDR.md" 2>/dev/null || echo "(not found)"
else
  # Fallback: synthesize from per-dir index.md files (OKF §8)
  CDR_COUNT=0
  for dir in rules personas examples; do
    idx="$TEAM_AI_DIRECTIVES/context_modules/$dir/index.md"
    if [ -f "$idx" ]; then
      # Extract type from heading, title/description from list items
      while IFS= read -r line; do
        if echo "$line" | grep -q '^\* \['; then
          title=$(echo "$line" | sed 's/^\* \[\([^]]*\)\].*/\1/')
          desc=$(echo "$line" | sed 's/^\* \[[^]]*\] *- *//')
          echo "| $dir/$title | $dir | $desc |"
          CDR_COUNT=$((CDR_COUNT + 1))
        fi
      done < "$idx"
    fi
  done
fi
echo ""
echo "_Total: $CDR_COUNT CDRs available._"
echo ""

# Class Boots — on-demand record-class context + decision capture.
# team-boot injects the always-relevant team context (constitution, CDR index,
# skills); each class boot loads its record-class index when a task or decision
# matches, and pairs it with decision capture via its -specify/-init skill.
echo "## Class Boots"
echo ""
echo "| Boot | Injects | Invoke When | Capture Via |"
echo "|--|--|--|--|"
echo "| architect-boot | ADR index (.adlc/memory/adr/) | architecture work; tech-stack/pattern choice | /architect-specify |"
echo "| product-boot | PDR index (.adlc/memory/pdr/) | product/feature scope, personas, monetization | /product-specify |"
echo "| change-boot | ChDR index (.adlc/memory/chdr.md) | change-history rationale, reverts, issue-linked commits | /change-init |"
echo "| levelup-boot | CDR module bodies (team-ai-directives) | CDR descriptor match; reusable team pattern | /levelup-specify |"
echo "| tech-radar-boot | Tikal Tech Radar context | choosing/evaluating technology | radar context + /architect-specify |"
echo ""
echo "Invoke a class boot when a task or decision matches its row. Each boot emits its class context section and its own searched line (_Searched N <class> records, K matched._)."
echo ""

# Skills — names + descriptions only (lean)
echo "## Available Skills"
SKILL_DEFAULT_COUNT=$(jq -r '.default | length' "$TEAM_AI_DIRECTIVES/.skills.json" 2>/dev/null || true)
SKILL_EXTERNAL_COUNT=$(jq -r '.external | length' "$TEAM_AI_DIRECTIVES/.skills.json" 2>/dev/null || true)
[[ "$SKILL_DEFAULT_COUNT" =~ ^[0-9]+$ ]] || SKILL_DEFAULT_COUNT=0
[[ "$SKILL_EXTERNAL_COUNT" =~ ^[0-9]+$ ]] || SKILL_EXTERNAL_COUNT=0
SKILL_TOTAL=$((SKILL_DEFAULT_COUNT + SKILL_EXTERNAL_COUNT))
jq -r '.default[]' "$TEAM_AI_DIRECTIVES/.skills.json" 2>/dev/null | while read -r name; do
  echo "- $name"
done || true
jq -r '.external | to_entries[] | "- \(.key): \(.value.description)"' "$TEAM_AI_DIRECTIVES/.skills.json" 2>/dev/null || true
echo ""
echo "_Total: $SKILL_TOTAL skills available._"
echo ""

# MCP Servers — names only (lean)
echo "## MCP Servers"
jq -r '.mcpServers | keys[]' "$TEAM_AI_DIRECTIVES/.mcp.json" 2>/dev/null | while read -r name; do
  echo "- $name"
done || echo "(none)"
echo ""

echo "Read full CDR.md, .skills.json, and context module files on demand when a task matches."
echo "Invoke the matching class boot when a task or decision matches a Class Boots row."
echo "Prefer targeted file searches over broad directory listings to conserve context."
echo ""
echo "**Every response MUST include** a Team Context in Use section before the task answer:"
echo "Match CDR entries and skills from the lists above to the current task."
echo ""
echo "## Team Context in Use"
echo ""
echo "| ID | Name | Type | Rel |"
echo "|--|--|--|--|"
echo "| CDR-YYYY-NNN | <name> | <type> | <relevance> |"
echo ""
echo "Plus: _Searched $CDR_COUNT CDRs, $SKILL_TOTAL skills, J matched._ (Class indexes are searched when their class boot is invoked — each reports its own line.)"
echo "**J MUST equal the number of rows in your table; if no CDRs/skills genuinely match, show an empty table with 0 matched (do not copy a hard-coded CDR or inflate the count).**"
echo ""
echo "## Decision Capture"
echo ""
echo "Detect decisions as they emerge; full detection and capture guidance lives in the matching class boot:"
echo "- Tech stack / pattern choice → ADR → /architect-specify (pull tech-radar-boot context first for tech selection)"
echo "- Feature scope / persona / monetization → PDR → /product-specify"
echo "- Reusable team rule / pattern → CDR → /levelup-specify"
echo "- Revert/hotfix rationale / issue-linked commit → ChDR → /change-init"
echo ""
echo "Maintain a running **Session Decision Ledger** visible in every response (after the Team"
echo "Context in Use table):"
echo ""
echo "| Decision | Type | Captured? | Skill |"
echo "|----------|------|-----------|-------|"
echo "| _none yet_ | — | — | — |"
echo ""
echo "_Unrecorded: N pending._"
echo ""
echo "- **Detect** decisions against the triggers above; **Classify** (ADR/PDR/CDR/ChDR);"
echo "  **Track** whether the matching skill was invoked; **Surface** unrecorded decisions."
echo "- **Session-end**: before closing, prompt to invoke the capture skills for any unrecorded decisions."
echo ""
echo "Only suggest when genuinely warranted — not on every response."

# Pending CDRs — remind user to clarify (safety net for missed suggestions)
if [ -d ".adlc/drafts/cdr" ]; then
  PENDING_CDRS=$(grep -rl "Status: \*\*Proposed\*\*" .adlc/drafts/cdr/CDR-*.md 2>/dev/null | wc -l || true)
  if [ "$PENDING_CDRS" -gt 0 ]; then
    echo ""
    echo "## Pending CDRs"
    echo "$PENDING_CDRS proposed CDR(s) awaiting review in \`.adlc/drafts/cdr/\`"
    echo "Run \`/levelup-clarify\` to accept, reject, or defer them."
  fi
fi

# Pending ADRs — remind user to clarify
if [ -d ".adlc/drafts/adr" ]; then
  PENDING_ADRS=$(grep -rl "status: proposed\|Status: Proposed" .adlc/drafts/adr/ADR-*.md 2>/dev/null | wc -l || true)
  if [ "$PENDING_ADRS" -gt 0 ]; then
    echo ""
    echo "## Pending ADRs"
    echo "$PENDING_ADRS proposed ADR(s) awaiting review in \`.adlc/drafts/adr/\`"
    echo "Run \`/architect-clarify\` to accept, reject, or defer them."
  fi
fi

# Pending PDRs — remind user to clarify
if [ -d ".adlc/drafts/pdr" ]; then
  PENDING_PDRS=$(grep -rl "status: proposed\|Status: Proposed" .adlc/drafts/pdr/PDR-*.md 2>/dev/null | wc -l || true)
  if [ "$PENDING_PDRS" -gt 0 ]; then
    echo ""
    echo "## Pending PDRs"
    echo "$PENDING_PDRS proposed PDR(s) awaiting review in \`.adlc/drafts/pdr/\`"
    echo "Run \`/product-clarify\` to accept, reject, or defer them."
  fi
fi

# Friction-based learning trigger (configurable, default on)
CONTRIBUTE_HINT=true
if [ -f "$INIT_FILE" ]; then
  HINT_VAL=$(grep '"contribute_hint"' "$INIT_FILE" 2>/dev/null \
    | sed 's/.*"contribute_hint"[[:space:]]*:[[:space:]]*\(true\|false\).*/\1/' \
    | head -1 || true)
  if [ -n "$HINT_VAL" ]; then CONTRIBUTE_HINT="$HINT_VAL"; fi
fi
if [ "$CONTRIBUTE_HINT" = "true" ]; then
  echo ""
  echo "## Session Friction Awareness"
  echo "After completing significant work, self-assess for decision drift:"
  echo ""
  echo "1. **CDR friction** — reusable patterns, novel approaches, or significant debugging emerged → suggest \`/levelup-specify\`"
  echo "2. **ADR gap** — new architectural concern not covered by existing ADRs → suggest \`/architect-specify\`"
  echo "3. **ADR violation** — work contradicts an accepted ADR → suggest \`/architect-clarify\`"
  echo "4. **PDR gap** — new product decision not covered by existing PDRs → suggest \`/product-specify\`"
  echo "5. **PDR violation** — work contradicts an accepted PDR → suggest \`/product-clarify\`"
  echo ""
  echo "Guardrail: Before assessing ADR/PDR alignment, read relevant ADR/PDR files from \`.adlc/memory/adr/\` and \`.adlc/memory/pdr/\` if not already loaded."
  echo "Do NOT suggest for routine work. At most one suggestion per task completion."
fi

echo "</EXTREMELY_IMPORTANT>"
