#!/usr/bin/env bash
# team-boot session_start script — lean orientation for first user message injection.
# Pure shell (grep/sed), no runtime dependencies.
set -euo pipefail

INIT_FILE=".adlc/init-options.json"

if [ ! -f "$INIT_FILE" ]; then
  echo "<EXTREMELY_IMPORTANT>"
  echo "Team AI directives not configured for this project."
  echo "Run /team-setup to wire in the team constitution, CDR index, PDR/ADR indexes, and skill registry."
  echo "</EXTREMELY_IMPORTANT>"
  exit 0
fi

# Extract team_ai_directives from JSON (pure shell, no runtime deps).
TEAM_AI_DIRECTIVES=$(grep '"team_ai_directives"' "$INIT_FILE" \
  | sed 's/.*"team_ai_directives"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/' \
  | head -1)

# Handle null marker (user opted out) or empty value.
if [ -z "$TEAM_AI_DIRECTIVES" ] || [ "$TEAM_AI_DIRECTIVES" = "null" ]; then
  exit 0
fi

# Verify path exists.
if [ ! -d "$TEAM_AI_DIRECTIVES" ]; then
  echo "<EXTREMELY_IMPORTANT>"
  echo "Team AI directives path not found: $TEAM_AI_DIRECTIVES"
  echo "Run /team-setup to reconfigure."
  echo "</EXTREMELY_IMPORTANT>"
  exit 0
fi

echo "<EXTREMELY_IMPORTANT>"
echo "# Team AI Directives"
echo ""
echo "Path: $TEAM_AI_DIRECTIVES"
echo ""

# Constitution — principle titles only (lean)
echo "## Constitution"
grep '^[0-9]\+\.' "$TEAM_AI_DIRECTIVES/context_modules/constitution.md" 2>/dev/null | head -20 || echo "(not found)"
echo ""

# CDR Index — compact: ID + Type + Descriptor only
# CDR.md is a derived flat table auto-generated by /team-repair from per-dir index.md files.
echo "## CDR Index"
if [ -f "$TEAM_AI_DIRECTIVES/CDR.md" ]; then
  CDR_COUNT=$(awk '/^\| CDR|^\| skill|^\| example/ {count++} END {print count+0}' "$TEAM_AI_DIRECTIVES/CDR.md" 2>/dev/null || echo "0")
  awk -F'|' '/^\| CDR|^\| skill|^\| example/ {gsub(/^ +| +$/,"",$2); gsub(/^ +| +$/,"",$4); gsub(/^ +| +$/,"",$9); print "| " $2 " | " $4 " | " $9 " |"}' "$TEAM_AI_DIRECTIVES/CDR.md" 2>/dev/null || echo "(not found)"
else
  # Fallback: synthesize from per-dir index.md files (OKF §8)
  CDR_COUNT=0
  for dir in rules personas examples; do
    idx="$TEAM_AI_DIRECTIVES/context_modules/$dir/index.md"
    if [ -f "$idx" ]; then
      # Extract type from heading, title/description from list items
      while IFS= read -r line; do
        if echo "$line" | grep -q '^\* \['; then
          title=$(echo "$line" | sed 's/^\* \[\([^]]*\)\].*/\1/')
          desc=$(echo "$line" | sed 's/^\* \[[^]]*\] *- *//')
          echo "| $dir/$title | $dir | $desc |"
          CDR_COUNT=$((CDR_COUNT + 1))
        fi
      done < "$idx"
    fi
  done
fi
echo ""
echo "_Total: $CDR_COUNT CDR entries available._"
echo ""

# Skills — names + descriptions only (lean)
echo "## Available Skills"
SKILL_DEFAULT_COUNT=$(jq -r '.default | length' "$TEAM_AI_DIRECTIVES/.skills.json" 2>/dev/null || echo "0")
SKILL_EXTERNAL_COUNT=$(jq -r '.external | length' "$TEAM_AI_DIRECTIVES/.skills.json" 2>/dev/null || echo "0")
SKILL_TOTAL=$((SKILL_DEFAULT_COUNT + SKILL_EXTERNAL_COUNT))
jq -r '.default[]' "$TEAM_AI_DIRECTIVES/.skills.json" 2>/dev/null | while read -r name; do
  echo "- $name"
done
jq -r '.external | to_entries[] | "- \(.key): \(.value.description)"' "$TEAM_AI_DIRECTIVES/.skills.json" 2>/dev/null || true
echo ""
echo "_Total: $SKILL_TOTAL skills available._"
echo ""

# MCP Servers — names only (lean)
echo "## MCP Servers"
jq -r '.mcpServers | keys[]' "$TEAM_AI_DIRECTIVES/.mcp.json" 2>/dev/null | while read -r name; do
  echo "- $name"
done || echo "(none)"
echo ""

echo "Read full CDR.md, .skills.json, and context module files on demand when a task matches."
echo "Prefer targeted file searches over broad directory listings to conserve context."
echo ""
echo "**Every response MUST include** a Team Context in Use section before the task answer:"
echo "Match CDR entries and skills from the lists above to the current task."
echo ""
echo "## Team Context in Use"
echo ""
echo "| ID | Name | Type | Relevance |"
echo "|----|------|------|-----------|"
echo "| CDR-YYYY-NNN | <name> | <type> | <relevance> |"
echo ""
echo "Plus: _Searched $CDR_COUNT CDR entries, $SKILL_TOTAL skills, J matched._"
echo "**J MUST equal the number of rows in your table; if no CDRs/skills genuinely match, show an empty table with 0 matched (do not copy a hard-coded CDR or inflate the count).**"
echo "</EXTREMELY_IMPORTANT>"
